### ISSUE TITLE
JavaScript: What is the difference between Local Storage and Session Storage? - needs an answer

### ISSUE THREAD

**Issue by monkey3310** [monkey3310/full-stack-interview#11]
**What content would you like to be covered**
Following question needs an answer:
### 6. What is the difference between Local Storage and Session Storage?

**Comment by pandaa880** [comment]
I will take this one, then.
😅

**Comment by pandaa880** [comment]
I have just one commit. How do i squash it ? I mean there no other commits, so should i just push the branch ?

**Comment by monkey3310** [comment]
@pandaa880 Just push it to your branch - it will be squash - merged to master when I click the merge button
