### ISSUE TITLE
React: Answers to question 1-5 needed

### ISSUE THREAD

**Issue by monkey3310** [monkey3310/full-stack-interview#24]
**What content would you like to be covered**
We need answers to questions 1 to 5 - if you are interested in creating a PR, let me know in this issue

**Comment by OmarAguinaga** [comment]
I would like to answer the questions but where are they?

**Comment by monkey3310** [comment]
@OmarAguinaga https://github.com/monkey3310/full-stack-interview/blob/master/tech/react.MD - feel free to submit PR 😄

**Comment by monkey3310** [comment]
Also, @OmarAguinaga if you feel like any of the question should be rephrased or a bit different / more precise - feel free to also edit it
