### ISSUE TITLE
JavaScript: Answer to 11. What is the difference between HTMLCollection and NodeList?

### ISSUE THREAD

**Issue by monkey3310** [monkey3310/full-stack-interview#26]
**What content would you like to be covered**
JavaScript: Answer to 11. What is the difference between HTMLCollection and NodeList?

**Comment by DinushaNaween** [comment]
Both interfaces are collections of DOM (Document Object Model ) nodes. They differ in the methods they provide and in the type of nodes they can contain. While a **NodeList** can contain any node type, an **HTMLCollection** is supposed to only contain Element nodes.
An **HTMLCollection** provides the same methods as a **NodeList** and additionally a method called **namedItem**.

Collections are always used when access has to be provided to multiple nodes, e.g. most selector methods (such as **getElementsByTagName**) return multiple nodes or getting a reference to all children (**element.childNodes**).

**Comment by monkey3310** [comment]
@DinushaNaween Thanks for the answer! Please submit your PR to the project with it 👍
