### ISSUE TITLE
Redux: Questions 6-10 are missing answers

### ISSUE THREAD

**Issue by monkey3310** [monkey3310/full-stack-interview#33]
**What content would you like to be covered**
We need to add answers to questions 6-10 in [Redux Interview Questions & Answers](https://github.com/monkey3310/full-stack-interview/blob/master/tech/redux.MD) 

PRs are welcome!

**Comment by showmeyourhits** [comment]
Hi. I would like to work on it. Can I work on it?

**Comment by monkey3310** [comment]
@showmeyourhits all yours!

**Comment by monkey3310** [comment]
FYI, 9. got already answered, but rest of the questions are still there :)
