### ISSUE TITLE
React: Answers for questions 6-10 needed

### ISSUE THREAD

**Issue by monkey3310** [monkey3310/full-stack-interview#38]
**What content would you like to be covered**
Answers for questions 6-10 needed. If you can, please rise a PR with answers

**Comment by harshini1** [comment]
@monkey3310  I see that questions do have answers, do you want us to improve it with examples and more info?

**Comment by harshini1** [comment]
I'll do that if its the expectation

**Comment by monkey3310** [comment]
@harshini1 Hey, I just merged the answers for react few sec ago, just didn't close this issue.
